### ISSUE TITLE
Shaderlab?

### ISSUE THREAD

**Issue by JBYT27** [darkdarcool/Color-the-World#1]
What's shaderlab? I see it in langs, but idk what it is lol.

Thanks!

**Comment by darkdarcool** [comment]
It makes cool colors lol, and the assets folder is the only one I make code in, all cs files are mine

**Comment by darkdarcool** [comment]
It's the first word of it that explains it, also go [here](https://forum.unity.com/threads/what-exactly-is-a-shaderlab.88153/) for the correct term

**Comment by JBYT27** [comment]
ok, thanks!

**Comment by darkdarcool** [comment]
Your welcome!

**Comment by darkdarcool** [comment]
also all cs files(every file except the .meta files) are the code files that I created, everything else is NOT code and most of it is not something I made, but you can ask. And a shortcut to code is [here](https://github.com/darkdarcool/Color-the-World/tree/main/Assets/Scenes/World/Scripts)
